imports:
    - { resource: service/controller/default.yaml }
    - { resource: service/controller/api.yaml }
    - { resource: service/repository.yaml }
    - { resource: service/http.yaml }
    - { resource: service/url.yaml }
    - { resource: service/transaction.yaml }
    - { resource: service/command.yaml }
    - { resource: service/query.yaml }
    - { resource: service/normalizer.yaml }

parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false