imports:
    - { resource: service/controllers.yaml }
    - { resource: service/repositories.yaml }
    - { resource: service/command/categories.yaml }

parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false